# Generated by Django 5.2.1 on 2025-05-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Đã thanh toán'), ('failed', 'Thất bại'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
